In [4]:
# Find the shape, size and dimension of the following array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

In [5]:
import numpy as np

In [8]:
array=np.array([[1,2,3,4],[5,5,7,8],[9,10,11,12]])

In [9]:
shape=array.shape

In [10]:
size=array.size

In [12]:
dimension=array.ndim

In [15]:
print("Shape of the array:",shape)
print("Size of the array:",size)
print("Dimension of the array:",dimension)

Shape of the array: (3, 4)
Size of the array: 12
Dimension of the array: 2


In [16]:
# Write python code to access the first row of the following array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

In [17]:
import numpy as np

In [18]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [19]:
first_row=array[0]


In [20]:
print("first row of the array:",first_row)

first row of the array: [1 2 3 4]


In [21]:
# How do you access the element at the third row and fourth column from the given numpy array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

In [22]:
import numpy as np

In [23]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [24]:
element=array[2,3]

In [25]:
print("elemnt at 3rd row and 4th column:", element)

elemnt at 3rd row and 4th column: 12


In [26]:
# Write code to extract all odd-indexed elements from the given numpy array?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

In [27]:
import numpy as np

In [28]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [31]:
flattened_array=array.flatten()

In [33]:
odd_element=flattened_array[1::2]

In [34]:
print("elements at odd index:",odd_element)

elements at odd index: [ 2  4  6  8 10 12]


In [36]:
# How to transpose the following array in NumPy?

#[[1, 2, 3, 4]
#[5, 6, 7, 8],
#[9, 10, 11, 12]]

In [37]:
 import numpy as np

In [38]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [40]:
transpose_array=np.transpose(array)

In [44]:
print("original aaray:", array)
print("Tranposed array is:",transpose_array)

original aaray: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Tranposed array is: [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
